### PR TITLE
Draft: replace full sdkconfig files with sdkconfig.defaults

### PR DESCRIPTION
**Pull request by igrr**
# 1st step: sdkconfig.TARGET -> sdkconfig.defaults.TARGET

In this step, sdkconfig file for each target is replaced with an sdkconfig.defaults file. All the options which are set to default values are removed, only the options different from the default values are kept.

This is done using `idf.py save-defconfig` script (cherry-picked from IDF commit 5118dd7c). ESP-IDF version used for generating the configs: v4.4 release tag.

Generated `sdkconfig` file is moved into the `build` directory.

The build scripts adjusted accordingly.

# 2nd step (TODO)

From the generated sdkconfig.defaults.TARGET files it can be seen that the settings for the 3 targets are different, even for some options which don't seem to be target-specific.

Need to make a list of all the options which aren't the same for the 3 targets and to check whether this is expected.

# Related

* Closes https://github.com/espressif/arduino-esp32/issues/6187.

### CODE REVIEW

**Comment by me-no-dev** [comment]
Seems that sdkconfig.defaults.TARGET are not applied when building. Is it possible that the build system expects them to be where sdkconfig will be generated? BTW what is the reason to relocate it to the build folder?

**Comment by Jason2866** [comment]
It would be nice if the `idf.py save-defconfig` would be backported to IDF4.4.
(Had to install idf master to be able to convert the sdkconfig files)
Thx!

**Comment by me-no-dev** [comment]
closing in favor of the s3 support branch, where such configs are used

**Comment by VojtechBartoska** [comment]
@me-no-dev Can I consider issue [6187](https://github.com/espressif/arduino-esp32/issues/6187) as closed?

**Comment by me-no-dev** [comment]
will be closed when we merge S3 support :)

**Pull request closed without merging**
