### PR TITLE
Added config for FAT label

### PR DESCRIPTION
**Pull request by lbernstone**
This activates the code for f_setlabel() and f_getlabel. These functions should take up less than 1k of symbol space.
Once these are available, I will add one-liner functions to the FFat and SD libraries to set/get volume name. I'm working on an example which exposes an SD card through the USBMSC, and being able to set the name would be a very nice touch.

### CODE REVIEW

**Comment by me-no-dev** [comment]
I guess we will need to add API for it in Arduino. Would you take the task?

**Comment by lbernstone** [comment]
@me-no-dev I'm not seeing this in the released libraries.  Has it just not been merged into arduino-lib yet?

**Comment by me-no-dev** [comment]
@lbernstone maybe it depends on something else?

**Comment by lbernstone** [comment]
Huh. Maybe I was just hallucinating that label.  In any case, it isn't used in IDF 5.1. This PR should be backed out.

**Pull request merged**
