### PR TITLE
Add configuration UI

### PR DESCRIPTION
**Pull request by lucasssvaz**
Arduino Static Libraries Configuration Editor

This is a simple application to configure the static libraries for the ESP32 Arduino core.
It allows the user to select the targets to compile, change the configuration options and compile the libraries.

The application is built using the 'textual' library, which is a Python library for building text-based user interfaces.

### To Do

- [x] Design screens (main menu, editor, options, compilation)
- [x] Create events for all UI elements
- [x] Update from/to variables the UI elements
- [x] Properly pipe build script output to UI (currently freezes until subprocess finishes, even running in background task)
  - [x] Fix target selection (bash script is ignoring target setting when executing from python script)
  - [x] Make error and success messages easier to see in the compilation log
- [x] Change naming to make it less confusing (something like "IDF Configuration Options" and "Library Compilation Settings")
- [x] Separate main menu screen from app
  - [x] Add key bindings to each screen
- [x] Change default Arduino folder to OS default
- [x] Make copying to Arduino optional
  - [x] Dynamically change settings screen based on switch value
- [x] Add branch selection and debug level for IDF. Improve settings screen.
- [x] Add optional arguments to override default values
- [ ] Make it pretty ✨ (any help is appreciated)
- [x] Write README

### CODE REVIEW

**Review by me-no-dev — APPROVED** [review]

**Comment by lucasssvaz** [comment]
@SuGlider @P-R-O-C-H-Y Do you guys want to take a look at the UI ? Or should we move on to the docker image implementation ?

**Comment by P-R-O-C-H-Y** [comment]
@lucasssvaz I am on it :)

**Comment by P-R-O-C-H-Y** [comment]
@lucasssvaz When #167 will get merged, it would be great to replace the `Compilation target` Selection with [SelectionList](https://textual.textualize.io/widgets/selection_list/), so multiple targets can be selected. Can you take a look? :)

**Comment by P-R-O-C-H-Y** [comment]
Else the UI is really nice! Awesome job.

**Review by P-R-O-C-H-Y — APPROVED** [review]
Great!

**Pull request merged**
