### PR TITLE
Currently components are taken from master which not always builds.

### PR DESCRIPTION
**Pull request by tomaszduda23**
Add command which recrate libs in the same version as in arduino-esp32.

### CODE REVIEW

**Comment by tomaszduda23** [comment]
It would be better to use android core as reference. Please review it first if you like idea I can change that.

**Comment by Jason2866** [comment]
Imho a good idea. Not the first time, this generates issues https://github.com/espressif/arduino-esp32/pull/7218
LittleFS was broken already too, not to build. It just didnt work anymore.

**Comment by me-no-dev** [comment]
still I do not like limiting all components to some version. It is like pinning IDF to some commit from now on. How would we get the new features and fixes? Keep in mind that this is a tool that is used to update Arduino's libs. It does not have to always build successfully :) @tomaszduda23 if you rework this to be able to specify only particular components, we can move forward with merging. Some have submodules and some do not and some that do have submodules should not fetch them (tinyusb)

**Comment by Jason2866** [comment]
Since i stumbled in this issue not only one time, i did choose a different approach. Forked IDF and integrated the needed stuff as submodules (easily update of used commit for a submodule). Left tinyusb in Arduino LibBuilder and using latest release version (without the unneeded submodules).
For our use case it is more important to use only the latest fixes/changes in IDF and Arduino and use known working 3rd party modules. Now it is up to us to decide when we want to use (test) new versions of the submodules. It is easier to check from time to time as finding issues coming "out of the dark".

**Comment by tomaszduda23** [comment]
I'm doing some project so I needed libs with debug logs. If it does not build is pretty painful to figure out was is wrong.
I do understand that someone wants to use latest so I added new flag.
```
echo " -r Recreate arduino-esp32 libs in give version"
```
If you don't use -r it should work old way. Build command look like that.
```
./build.sh -I v4.4.2 -r -t esp32s2
```

**Comment by tomaszduda23** [comment]
You need to specify git hash to rebuild in specific version so you can just export some of them if you would like to update one by one. For me important point I that I'm able to have the same libs version as in release.
```
AR_REPO_VERSION=55d608e3
CAMERA_REPO_VERSION=5611989
DL_REPO_VERSION=f3006d7
SR_REPO_VERSION=b578f17
RMAKER_REPO_VERSION=3736c12
DSP_REPO_VERSION=401faf8
LITTLEFS_REPO_VERSION=485a037
TINYUSB_REPO_VERSION=111515a29
```

**Comment by tomaszduda23** [comment]
> Since i stumbled in this issue not only one time, i did choose a different approach. Forked IDF and integrated the needed stuff as submodules (easily update of used commit for a submodule). Left tinyusb in Arduino LibBuilder and using latest release version (without the unneeded submodules).

I though about this also but I wanted to keep backward compatibility since I don't know all use cases for this.

**Comment by Jason2866** [comment]
@tomaszduda23 I do find your solution nice! Would have choosen this way, if bash scripting would be not so...

**Comment by tomaszduda23** [comment]
Any update?

**Pull request closed without merging**
