### PR TITLE
sdkconfig: Add CONFIG_LWIP_IPV6_AUTOCONFIG for IPv6 SLAAC

### PR DESCRIPTION
**Pull request by nuclearcat**
To use IPv6 we need proper SLAAC support which is not possible without this option.
Compile tested on esp32, esp32s2, esp32s3, esp32c3
Functionality tested in esp32 BasicHttpClient with some minor patches, IPv6 start to work.

No significant sketch size increase (probably within rounding bounds):
Before:
Wrote 875328 bytes (558896 compressed) at 0x00010000 in 9.0 seconds (effective 779.4 kbit/s)...
After:
Wrote 875328 bytes (558942 compressed) at 0x00010000 in 9.0 seconds (effective 779.8 kbit/s)...

This patch part of the efforts mentioned in https://github.com/espressif/arduino-esp32/issues/6242

Proper IPv6 support also was requested in:
https://github.com/espressif/arduino-esp32/issues/6626
https://github.com/espressif/arduino-esp32/issues/6590
https://github.com/espressif/arduino-esp32/issues/6283
https://github.com/espressif/arduino-esp32/issues/6703
https://github.com/espressif/arduino-esp32/issues/5624
https://github.com/espressif/arduino-esp32/issues/1261
And many others.

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>

### CODE REVIEW

**Comment by me-no-dev** [comment]
Please add the config to https://github.com/espressif/esp32-arduino-lib-builder/blob/master/configs/defconfig.common instead :)

**Comment by nuclearcat** [comment]
Done.
I was not sure about this, as i thought - what if one of chips have problems with this feature (especially new one that might be Zigbee/BLE only). But i guess if problem will appear, we will solve it :)

**Comment by me-no-dev** [comment]
> I was not sure about this, as i thought - what if one of chips have problems with this feature (especially new one that might be Zigbee/BLE only). But i guess if problem will appear, we will solve it :)

A battle for another day :D We will sort this out once we start adding H2 support

**Comment by nuclearcat** [comment]
Rebased, any feedback? :)

**Comment by me-no-dev** [comment]
Sorry for the delay :) had to sort out some other issues first. Now merged!

**Pull request merged**
