### PR TITLE
Use flash_mode for memory_type when memory_type is not set for

### PR DESCRIPTION
**Pull request by Jason2866**
…ESP32, C3 and S2 when using Platformio

Replaces https://github.com/espressif/arduino-esp32/pull/7141

### CODE REVIEW

**Comment by Jason2866** [comment]
This change is tested and verified. Builded framework is working

**Comment by me-no-dev** [comment]
Can you please replace `dout` with `dio` as `dout` is not available for all boards, where `dio` is left for compatibility.

**Comment by Jason2866** [comment]
@me-no-dev  Changed. I always thought `dout` is slowest most compatible mode

**Comment by me-no-dev** [comment]
> @me-no-dev Changed. I always thought `dout` is slowest most compatible mode

it is, but it is unnecessary on boards other than one very specific ESP32 based one. So to save on libs and bootloaders, it has been removed on S3 and probably will do for C3 and S2 in the future.

**Pull request merged**
