### PR TITLE
Fix: increase ESP32-S3 Bluetooth tasks stack size to 8k

### PR DESCRIPTION
**Pull request by Dabolus**
This PR updates the ESP32-S3 Bluetooth tasks stack size to 8k as it was already done for the standard ESP32 to avoid the crashes that happen when connecting to some devices such as the Polar H10 heart monitor.
See [this issue](https://github.com/espressif/arduino-esp32/issues/6063) for more context/information.

### CODE REVIEW

**Comment by me-no-dev** [comment]
if this is causing issues on more than one board, would it not make sense to set it for all chips?

**Comment by Dabolus** [comment]
I did the change only to the ESP32-S3 because I'm not sure how the other chips behave as I don't own them, but if you're okay with that I can also just move the two options to `defconfig.common`. WDYT?

**Comment by me-no-dev** [comment]
yes please :)

**Comment by Dabolus** [comment]
Done ✅

**Comment by Dabolus** [comment]
Sorry, I had committed with the front email address. Now it should be fine.

**Comment by Dabolus** [comment]
@me-no-dev do the changes look good now? Can this be merged?

**Comment by me-no-dev** [comment]
yes, will merge soon.

**Comment by Dabolus** [comment]
Great, thanks! ✨

**Pull request merged**
