### PR TITLE
skip etherent patch if already applied

### PR DESCRIPTION
**Pull request by Jason2866**

### CODE REVIEW

**Comment by brentru** [comment]
@Jason2866  Seems to be a failure here (I am running into the same thing on my fork :) ) :

```
Compilation failed because esp32-hal-sr.c (in "arduino" component) includes esp_mn_speech_commands.h, provided by esp-sr component(s).
However, esp-sr component(s) is not in the requirements list of "arduino".
To fix this, add esp-sr to PRIV_REQUIRES list of idf_component_register call in /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/components/arduino/CMakeLists.txt.
```

However, the file `/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/components/arduino/CMakeLists.txt` is not present in `master`...

**Comment by Jason2866** [comment]
@brentru I removed SR (and other stuff) we don't need / use. So no issue for me.

**Comment by me-no-dev** [comment]
Though unrelated, please add `esp-sr` to `PRIV_REQUIRES` or `REQUIRES` in `CMakeLists.txt`.

**Comment by brentru** [comment]
@me-no-dev  This (https://github.com/espressif/esp32-arduino-lib-builder/blob/master/CMakeLists.txt) CMakeLists.txt, or another one? The one in root doesn't contain `PRIV_REQUIRES` or `REQUIRES`.

**Comment by Jason2866** [comment]
> @me-no-dev This (https://github.com/espressif/esp32-arduino-lib-builder/blob/master/CMakeLists.txt) CMakeLists.txt, or another one? The one in root doesn't contain `PRIV_REQUIRES` or `REQUIRES`.

This one https://github.com/espressif/arduino-esp32/blob/master/CMakeLists.txt

**Pull request merged**
